# Generated by Django 4.2.6 on 2023-10-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('reduction', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bar')),
            ],
        ),
    ]
