# Generated by Django 4.2.6 on 2023-10-21 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('completed', models.BooleanField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('end_datetime__gt', models.F('initial_datetime'))), name='end_datetime_check'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('table', 'initial_datetime')},
        ),
    ]
