# Generated by Django 4.2.6 on 2023-11-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking_booking_end_datetime_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
