# Generated by Django 4.2.6 on 2023-12-20 22:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_bar_description_alter_bar_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='phone',
            field=models.CharField(max_length=30, validators=[api.models.Bar.validate_phone]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=30, validators=[api.models.UserProfile.validate_phone]),
        ),
    ]
