# Generated by Django 4.2.6 on 2023-12-21 18:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_bar_phone_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='address',
            field=models.CharField(max_length=100, validators=[api.models.Bar.validate_address]),
        ),
        migrations.AlterField(
            model_name='bar',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, validators=[api.models.Bar.validate_description]),
        ),
        migrations.AlterField(
            model_name='bar',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[api.models.Bar.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='bar',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[api.models.Bar.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='bar',
            name='name',
            field=models.CharField(max_length=20, validators=[api.models.Bar.validate_name]),
        ),
    ]
