version: '3.1'

services:

  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: barliuser
      POSTGRES_PASSWORD: barlipass
      POSTGRES_DB: barlibd

    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:6.14
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: barli@barli.com
      PGADMIN_DEFAULT_PASSWORD: barli_password
    ports:
      - 5002:80
    depends_on:
      - postgres
